In [1]:
import numpy as np


In [2]:
print(np.__version__)

2.3.5


In [3]:
data = np.array([1,2,3,4])
print(data)
print(type(data))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
data = data + 2
print(data)

[3 4 5 6]


In [5]:
num = np.array([10,20,30,40])
print(sum(num))

100


In [6]:
numlist = np.arange(1,1000001)
print(np.sum(numlist))

500000500000


In [7]:
import time

num = list(range(1,10000001))
total = 0
timestart = time.time()
for i in num:
    total += i
timeend = time.time()
print(total)
print(f'Time took to calculate is : {timeend - timestart}') 

50000005000000
Time took to calculate is : 0.8708679676055908


In [8]:
numbers = np.arange(1,10000001)
start_time = time.time()     # provide some start time
print(np.sum(numbers))
end_time = time.time()     # provide some end time
print(f"Total Time Taken : {end_time-start_time:.4f}")

50000005000000
Total Time Taken : 0.0055


In [9]:
# In Numpy Speed Is Better
import time
numbers = list(range(1,10000001))
total = 0
start_time = time.time()     # provide some start time
for n in numbers:
    total += n
end_time = time.time()     # provide some end time
print(total)
print(f"Total Time Taken : {end_time-start_time:.4f}")

50000005000000
Total Time Taken : 0.7975


In [10]:
# Array
# In programming Array is a data structure [collection of data elements]
# Array is denoted by using []
# Array is a collection of similar data types
 
list1 = [10,78.21,"Python",True]
print(list1)
 
arr = np.array([10,78.21,"Python",True])  # smaller data types will be converted to higher data type
print(arr)

[10, 78.21, 'Python', True]
['10' '78.21' 'Python' 'True']


In [11]:
# array() --> used to create 1D and 2D array
# This is a 1D array

arr1 = np.array([12,22,32,42,52])
print(arr1)
 # This is a 2D array
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9],['',0,'']])
print(f'\n{arr2}')

[12 22 32 42 52]

[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']
 ['' '0' '']]


In [12]:
# if you are using a property   :   propertyname
# if you are using a method     :   methodname()

In [13]:
# if you are using a property   :   propertyname

# if you are using a method     :   methodname()
 
# shape property

# help us to determine the dimension of an array
 
# for 1D array shape property returns n,

# where n is the number of elements
 
# for 2D array shape property returns n,m

# where n is the number of rows and m is the number of columns
 
print(arr1.shape)

print(arr2.shape)

(5,)
(4, 3)


In [14]:
# Task 
# create a 3x4 and  5x2 2D array

arr1 = np.array([[2,4,6,8,],[10,12,14,16],[18,20,22,24]])
print(arr1)

arr2 = np.array([[10,20],[30,40],[50,60],[70,80],[90,100]])
print(f'\n{arr2}')

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

[[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]]


In [15]:
# Numpy Array Is A Sequence + Iterable
arr = np.array([10,20,30,40,50,60,70,80,90,100])
print(arr)

# 1D  
# Indexing And Slicing
print(arr[0])
print(arr[-1])
print(arr[::-1])
print(arr[1:5])

# loops
for i in arr:
    multi = i*2
    print(multi)

for i in enumerate(arr):
    print(i)

[ 10  20  30  40  50  60  70  80  90 100]
10
100
[100  90  80  70  60  50  40  30  20  10]
[20 30 40 50]
20
40
60
80
100
120
140
160
180
200
(0, np.int64(10))
(1, np.int64(20))
(2, np.int64(30))
(3, np.int64(40))
(4, np.int64(50))
(5, np.int64(60))
(6, np.int64(70))
(7, np.int64(80))
(8, np.int64(90))
(9, np.int64(100))


In [16]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
 
'''  
    c0    c1   c2
ro   1    2     3              0,0    0,1  0,2
r1   4    5     6              1,0    1,1  1,2
r2   7    8     9              2,0    2,1  2,2
 
'''
 
print(arr[2,1])
print(arr[0,2])
 
# print only first row
print(arr[0])    # 1 2 3
 
# print only third row
print(arr[2])    # 1 2 3
 
# print only second column
# syntax  arr[:,column]  for column only use comma before indexNumber
print(arr[:,1])
 
# print only third column
print(arr[:,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
8
3
[1 2 3]
[7 8 9]
[2 5 8]
[3 6 9]


In [17]:
# NUMPY data types

# dtype property

# this property help us to determine the data type of an array
 
# int 

arr = np.array([45,65,120,78,11,89])

print(arr.dtype)
 
arr = np.array([45,65,120,78,11,89],dtype='int8')   # int8 --> 8bits  int32 --> 32bits   int64 --> 64bits

print(arr.dtype)
 
marks = np.array([45,65,100,78,11,89],dtype='int8')

print(arr.dtype)
print(marks.dtype)
 

int64
int8
int8
int8


In [18]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)

arr = np.array([True,False,False])
print(arr.dtype)

arr = np.array([1.1,1.2,1.3,1.4,1.5])
print(arr.dtype)

arr = np.array(['Roy','Analyst','Data'])
print(arr.dtype)

int64
bool
float64
<U7


In [19]:
arr = np.array([1.1,1.2,1.3,1.4,1.5])
arr = arr.astype('int32')
print(arr)
print(arr.dtype)

arr = np.array([1.1,1.2,1.3,1.4,1.5],dtype='int8')
print(arr.dtype)


[1 1 1 1 1]
int32
int8


In [20]:
# copy() vs view()
# copy()
# create the copy of an array in a different memory location

# if you make any changes in copied_array it won't affect the original array
# if you make any changes in original_array it won't affect the copied array

arr = np.array([1,2,3,4,5])
copy_arr = arr.copy()
arr[4] = 10
print(f'Original array :{arr}')
print('Copied Array :' ,copy_arr)

Original array :[ 1  2  3  4 10]
Copied Array : [1 2 3 4 5]


In [21]:
# view()
# is the representation of the original array
# it shares the same memory location
# if you make any changes in copied_array it will affect the original array

arr = np.array([1,2,3,4,5])
copy_arr = arr.view()
arr[4] = 10

print(f'Original array :{arr}')
print(f'Copied Array : {copy_arr}')

# shares_memory() --> returns TRUE if arrays are sharing same memory location

print(f'\n',np.shares_memory(arr,copy_arr))

Original array :[ 1  2  3  4 10]
Copied Array : [ 1  2  3  4 10]

 True


In [22]:
# 1D to 2D

arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
twoD = arr.reshape(5,2)
print(twoD)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [23]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11])
print(arr)
twoD = arr.reshape(11,1)
print(twoD)
print(twoD.shape)

[ 1  2  3  4  5  6  7  8  9 10 11]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
(11, 1)


In [32]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])

# numpy.newaxis

# is used to increase the dimension of the existing array by adding

# one more dimension to it.

# 1D array will become 2D array

arr[np.newaxis,:]        #Row Vector


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13]])

In [31]:
arrC = arr[:,np.newaxis] #Collumn Vector
print(arrC)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]]


In [36]:
# 2D to 1D

twoD = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(twoD)
oneD = twoD.reshape(9)
print(oneD)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [37]:
twoD = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(twoD)
oneD = twoD.reshape(-1)
print(oneD)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [44]:
twoD = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(twoD)
print(twoD.shape)
oneD = twoD.flatten()
print('\n',oneD)
print(oneD.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)

 [1 2 3 4 5 6 7 8 9]
(9,)


In [46]:
# Concatenate
# Used to join multiple Arrays

arr = np.array([1,2,3,4,5])
arr1 = np.array([6,7,8,9,10])
arr2 = np.array([11,12,13,14,15])
arrc = np.concatenate((arr,arr1,arr2))
print(arrc)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [56]:
arr = np.array([[1,2],[4,5]])
arr1 = np.array([[6,7],[9,10]])
arr2 = np.array([[11,12],[14,15]])
arrc = np.concatenate((arr,arr1,arr2))
print(arrc)
print(arrc[5,1])

[[ 1  2]
 [ 4  5]
 [ 6  7]
 [ 9 10]
 [11 12]
 [14 15]]
15


In [59]:
# array_split()

arr = np.array([1,2,3,4,5,6,7,8,9,10])
np.array_split(arr,2)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [63]:
# Sorting

# np.sort()   # by default ascending order

prices = np.array([78,34,56,90,102,34,12,67,34,120,172,95])
print(np.sort(prices))


[ 12  34  34  34  56  67  78  90  95 102 120 172]


In [66]:
# Sorting in a descending order

prices = np.array([78,34,56,90,102,34,12,67,34,120,172,95])
print(np.sort(prices)[::-1])


[172 120 102  95  90  78  67  56  34  34  34  12]


In [73]:
# Filtering and Search

arr = np.array([1,4,2,7,9,3,5,8])
print(arr)
arr = arr[arr>=5]   # Boolean Masking
print(arr)

[1 4 2 7 9 3 5 8]
[7 9 5 8]


In [68]:
prices = np.array([1,4,2,7,9,3,5,8])
print(arr)
 
print(np.sort(prices)[4::])

[1 4 2 7 9 3 5 8]
[5 7 8 9]


In [95]:
# not divisibe by 2
arr = np.array([1,4,2,7,9,3,5,8,12,14,13,9,6,5,11,7])
arr%2!=0
arr = arr[arr%2!=0] 
print(arr)

[ 1  7  9  3  5 13  9  5 11  7]


In [101]:
# not divisibe by 2 and should be greater than 7
arr = np.array([1,4,2,7,9,3,5,8,12,14,13,9,6,5,11,7])
arr%2!=0
arr>7
arr = arr[(arr%2!=0)&(arr>7)]
print(arr)



[ 9 13  9 11]


In [104]:
# np.where(expression)

arr = np.array([1,4,2,7,9,3,5,8,12,14,13,9,6,5,11,7])
res = np.where((arr>=7) & (arr%2!=0))
print(arr[res])
print(f"Index Number :",res)

[ 7  9 13  9 11  7]
Index Number : (array([ 3,  4, 10, 11, 14, 15]),)


In [108]:
arr = np.array([10, 32, 30, 50, 20, 82, 91, 45])

# Find indices where value is 30
indices = np.where(arr == 30)
print(f"Indices where value is 30: {indices}")

# Find indices where values are even
even_indices = np.where(arr % 2 == 0)
print(f"Indices of even values: {even_indices}")

# Conditional selection
new_arr = np.where(arr > 40 ,arr * 2 ,arr)
print(f"Array after conditional selection: {new_arr}")

Indices where value is 30: (array([2]),)
Indices of even values: (array([0, 1, 2, 3, 4, 5]),)
Array after conditional selection: [ 10  32  30 100  20 164 182  90]


In [110]:
# Numpy random Module

from numpy import random
x = random.randint(100)
print(x)

55


In [112]:
# 1D

x = random.randint(100,size=(10))
print(x)

[21 96 59 84 90 31 84 70 66 55]


In [113]:
# 2D

x = random.randint(100,size=(3,3))
print(x)

[[80 44 99]
 [86 50 98]
 [72 39 44]]


In [114]:
# rand()

# generate a random float value between 0 and 1

x = random.rand()
print(x)
 

0.17491705913849898


In [116]:
# 1D

x = random.rand(10)
print(x)

[0.54403716 0.93207169 0.81078591 0.57076587 0.67343228 0.1708765
 0.15490516 0.79744952 0.45831859 0.8661598 ]


In [117]:
# 2D

x = random.rand(3,3)
print(x)
 

[[0.83401238 0.09071075 0.20287352]
 [0.45245524 0.93354769 0.06298563]
 [0.20550285 0.63024835 0.48382775]]


In [119]:
# The choice() method allows you to generate a random value
# based on array of values

x = random.choice([1,4,6,9])
print(x)

6


In [122]:
x = random.choice([1,4,6,9],size=(10))
print(x)

[4 9 1 4 1 9 4 1 4 4]


In [124]:
x = random.choice([1,4,6,9],size=(3,3))
print(x)

[[1 1 6]
 [9 4 9]
 [9 9 9]]


In [125]:
# numpy.zeros()
# this function allows us to create an array filled with Zeros 0
# default data type will be Float

x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [126]:
x = np.zeros((3,3),dtype='i')
print(x)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [127]:
# numpy.ones()
# this function allows us to create an array filled with Ones 1
# default data type will be Float

x = np.ones(10)
print(x)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [133]:
x = np.zeros((3,3),dtype='i')
print(x)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [136]:
# numpy.sum()
# used to compute the sum of all elements

x = random.randint((50),size=(10))
print(x)
print(np.sum(x))

[16 27 33 18 34 10 38  3 47 33]
259


In [138]:
# numpy.mean()
# Shows the mean

x = random.randint((50),size=(10))
print(x)
print(np.mean(x))

[26  6  0 36 20 16 21 33 33 30]
22.1


In [141]:
# mode()
# Shows the mod (num that appears the most)

from scipy import stats

x = random.randint((50),size=(10))
print(x)
print(stats.mode(x))

[32  0 27 37 44 42 41 29 46 32]
ModeResult(mode=np.int32(32), count=np.int64(2))


In [154]:
# numpy.unique()
# return unique elements as a sorted array
a = np.unique([1,2,3,4,5,1,2,3,6,7,8,5,6,7,8,11,10,15,10,11,13,14,6])
print(a)

# Expected Output : [ 1  2  3  4  5  6  7  8 11 10 15 13 14]
# Return          : [ 1  2  3  4  5  6  7  8 10 11 13 14 15]

x = random.randint((50),size=(10))
print(x)
print(np.unique(x))



[ 1  2  3  4  5  6  7  8 10 11 13 14 15]
[40 16 46 33 22 25 31  3 31  1]
[ 1  3 16 22 25 31 33 40 46]


In [145]:
arr = np.array([1,2,3,4,5,1,2,3,6,7,8,5,6,7,8,11,10,15,10,11,13,14,6])
uv , i = np.unique(arr,return_index=True)
print(uv) # unique_values
print(i) # index Numbers

[ 1  2  3  4  5  6  7  8 10 11 13 14 15]
[ 0  1  2  3  4  8  9 10 16 15 20 21 17]


In [146]:
# argsort --> reorder based on original appearance
uv[np.argsort(i)]
 
# [ 1  2  3  4  5  6  7  8 10 11 13 14 15]
# [ 0  1  2  3  4  8  9 10 16 15 20 21 17]
 
# re order --> [ 0  1  2  3  4  8  9 10 15 16 17 20 21]

array([ 1,  2,  3,  4,  5,  6,  7,  8, 11, 10, 15, 13, 14])

In [160]:
# arange()

print(np.arange(10))
print(np.arange(1,10))
print(np.arange(1,10,2))

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [161]:
x = np.arange(1,10)
print(x)

[1 2 3 4 5 6 7 8 9]


In [157]:
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [162]:
# Numpy Broadcasting
 
arr1 = np.array([5,8,10,12])
arr2 = np.array([3,7,6,5])
 
print(arr1+arr2)
print(arr1*arr2)

[ 8 15 16 17]
[15 56 60 60]


In [163]:
# Broadcasting cannot perform arithmetic operations with different shapes


arr1 = np.array([5,8,10,12])
arr2 = np.array([3,7])
 
print(arr1+arr2)
print(arr1*arr2)

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [164]:
# General Rules To Avoid Broadcasting
 
# a.) both array dimensions should be equal
# b.) if any of them is 1
 
arr1 = np.array([5,8,10,12])
arr2 = np.array([3])
 
print(arr1+arr2)

[ 8 11 13 15]
